baseURL = "https://mynewhugosite.com"
title = "My Site"

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 20

  [[menu.main]]
    identifier = "pics"
    name = "Pics"
    url = "/pics"
    weight = 30
